package com.szymc.voxel_engine;
public class Blocks {
	public static final byte AIR = 0;
	public static final byte GRASS = 1;
	public static final byte DIRT = 2;
	public static final byte OAK_WOOD = 3;
	public static final byte OAK_LEAVES = 4;
	public static final byte STONE = 5;
	public static final byte WATER = 6;
	public static final byte SAND = 7;
	public static final byte GRAVEL = 8;
	public static final byte BEDROCK = 9;
	public static final byte LAVA = 10;
	public static final byte BIRCH_WOOD = 11;
	public static final byte BIRCH_LEAVES = 12;
	public static final byte SNOW = 13;
	public static final byte SAVANNA_GRASS = 14;
	public static final byte JUNGLE_GRASS = 15;
	public static final byte TAIGA_GRASS = 16;
	public static final byte TUNDRA_GRASS = 17;
	public static final byte ICE = 18;
	public static final byte GRASS_DECORATION = 19;
	public static final byte FOREST_GRASS = 20;
	public static final byte BIRCH_GRASS = 21;
	public static final byte SPRUCE_LOG = 22;
	public static final byte SPRUCE_LEAVES = 23;
	public static final byte ACACIA_LOG = 24;
	public static final byte ACACIA_LEAVES = 25;
	public static final byte SNOWY_SPRUCE_LEAVES = 26;
}